apiVersion: v1
kind: Service
metadata:
  name: school-system-service
spec:
  type: NodePort
  selector:
    app: school-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
