spring.datasource.url=jdbc:mariadb://localhost:3306/School
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
security.jwt.secret-key=cb2c587824ffa96c4e6249d72c3eb17e0c72d6a24686194302fccbb364bbde4e
security.jwt.expiration-time=604800000
server.port=8080